title:             redgura
email:             redgura@gmail.com
description:       새빨간거짓말
author:            redgura
baseurl:           "/"
url:               "http://redgura.github.io"


# Social Profiles
twitter_username:  redgura
github_username:   redgura
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
theme: jekyll-theme-clean-blog
